const movies = [
  {
    "title": "(500) Days Of Summer",
    "trailer": "https://www.youtube.com/embed/PsD0NpFSADM?controls=0",
    "imdb": "https://www.imdb.com/title/tt1022603/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "50 first dates",
    "trailer": "https://www.youtube.com/embed/Q_2AbjYeSMI?controls=0",
    "imdb": "https://www.imdb.com/title/tt0343660/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Amelié",
    "trailer": "https://www.youtube.com/embed/HUECWi5pX7o?controls=0",
    "imdb": "https://www.imdb.com/title/tt0211915/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Arrival",
    "trailer": "https://www.youtube.com/watch?v=AMgyWT075KY",
    "imdb": "https://www.imdb.com/title/tt2543164/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Beauty and The Beast",
    "trailer": "https://www.youtube.com/watch?v=9Z9T1AR3b7s",
    "imdb": "https://www.imdb.com/title/tt0101414/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Before Midnight",
    "trailer": "https://www.youtube.com/watch?v=Kv6JWoVKlGY",
    "imdb": "https://www.imdb.com/title/tt2209418/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Before sunrise",
    "trailer": "https://www.youtube.com/watch?v=6MUcuqbGTxc",
    "imdb": "https://www.imdb.com/title/tt0112471/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Before Sunset",
    "trailer": "https://www.youtube.com/watch?v=oI3UuneLcyU",
    "imdb": "https://www.imdb.com/title/tt0381681/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Belly",
    "trailer": "https://www.youtube.com/watch?v=t_UmdGYNPjg",
    "imdb": "https://www.imdb.com/title/tt0158493/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Big Daddy",
    "trailer": "https://www.youtube.com/watch?v=jxnccxgybUI",
    "imdb": "https://www.imdb.com/title/tt0142342/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Borat",
    "trailer": "https://www.youtube.com/watch?v=iJZO5Hge2DY",
    "imdb": "https://www.imdb.com/title/tt0443453/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Bruno",
    "trailer": "https://www.youtube.com/watch?v=9dAc_sfTpFs",
    "imdb": "https://www.imdb.com/title/tt0889583/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Cast Away",
    "trailer": "https://www.youtube.com/watch?v=qGuOZPwLayY",
    "imdb": "https://www.imdb.com/title/tt0162222/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Catch Me If You Can",
    "trailer": "https://www.youtube.com/watch?v=s-7pyIxz8Qg",
    "imdb": "https://www.imdb.com/title/tt0264464/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Children of Men",
    "trailer": "https://www.youtube.com/watch?v=5e1HomFYPtc",
    "imdb": "https://www.imdb.com/title/tt0206634/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Chungking Express",
    "trailer": "https://www.youtube.com/watch?v=Bjd7PFf_TFw",
    "imdb": "https://www.imdb.com/title/tt0109424/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Clockwork Orange",
    "trailer": "https://www.youtube.com/watch?v=SPRzm8ibDQ8",
    "imdb": "https://www.imdb.com/title/tt0066921/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Coffy",
    "trailer": "https://www.youtube.com/watch?v=WMSAUcZtc9o",
    "imdb": "https://www.imdb.com/title/tt0069897/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Coming to America",
    "trailer": "https://www.youtube.com/watch?v=vPE4OCeKt2k",
    "imdb": "https://www.imdb.com/title/tt0094898/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Crazy Rich Asians",
    "trailer": "https://www.youtube.com/watch?v=ZQ-YX-5bAs0",
    "imdb": "https://www.imdb.com/title/tt3104988/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Django",
    "trailer": "https://www.youtube.com/watch?v=ztD3mRMdqSw",
    "imdb": "https://www.imdb.com/title/tt1853728/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Eat Pray Love",
    "trailer": "https://www.youtube.com/watch?v=NS8lWPIkyL8",
    "imdb": "https://www.imdb.com/title/tt0879870/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Enough",
    "trailer": "https://www.youtube.com/watch?v=1gS2nXsB_jY",
    "imdb": "https://www.imdb.com/title/tt0278435/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Ferris Bueller's Day Off",
    "trailer": "https://www.youtube.com/watch?v=D6gABQFR94U",
    "imdb": "https://www.imdb.com/title/tt0091042/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Footloose",
    "trailer": "https://www.youtube.com/watch?v=P4narQca4Oc",
    "imdb": "https://www.imdb.com/title/tt0087277/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Friday",
    "trailer": "https://www.youtube.com/watch?v=umvFBoLOOgo",
    "imdb": "https://www.imdb.com/title/tt0113118/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Friday After Next",
    "trailer": "https://www.youtube.com/watch?v=gttd475_yMw",
    "imdb": "https://www.imdb.com/title/tt0293815/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Get Out",
    "trailer": "https://www.youtube.com/watch?v=sRfnevzM9kQ",
    "imdb": "https://www.imdb.com/title/tt5052448/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Gone Girl",
    "trailer": "https://www.youtube.com/watch?v=0VGD_jLyE9Y",
    "imdb": "https://www.imdb.com/title/tt2267998/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Good Will Hunting",
    "trailer": "https://www.youtube.com/watch?v=DyiPHC_VQFY",
    "imdb": "https://www.imdb.com/title/tt0119217/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Goodfellas",
    "trailer": "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
    "imdb": "https://www.imdb.com/title/tt0099685/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Grand Budapest Hotel",
    "trailer": "https://www.youtube.com/watch?v=hgGXL5lJ-6g",
    "imdb": "https://www.imdb.com/title/tt2278388/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Guess Who's Coming to Dinner",
    "trailer": "https://www.youtube.com/watch?v=YZycqHfmrzQ",
    "imdb": "https://www.imdb.com/title/tt0061735/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Half Baked",
    "trailer": "https://www.youtube.com/watch?v=HMhUnO2u6qI",
    "imdb": "https://www.imdb.com/title/tt0120693/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Heathers",
    "trailer": "https://www.youtube.com/watch?v=hf6OhBKksKg",
    "imdb": "https://www.imdb.com/title/tt0097493/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Hereditary",
    "trailer": "https://www.youtube.com/watch?v=3e_yI2_Mu3g",
    "imdb": "https://www.imdb.com/title/tt7784604/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Hitch",
    "trailer": "https://www.youtube.com/watch?v=pYrrEUgnT6s",
    "imdb": "https://www.imdb.com/title/tt0386588/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Honey, I Shrunk The Kids",
    "trailer": "https://www.youtube.com/watch?v=L9nCNJ3cZSk",
    "imdb": "https://www.imdb.com/title/tt0097523/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "I Am Legend",
    "trailer": "https://www.youtube.com/watch?v=dtKMEAXyPkg",
    "imdb": "https://www.imdb.com/title/tt0480249/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Inception",
    "trailer": "https://www.youtube.com/watch?v=97CDCk2n-Nw",
    "imdb": "https://www.imdb.com/title/tt1375666/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Independence Day",
    "trailer": "https://www.youtube.com/watch?v=B1E7h3SeMDk",
    "imdb": "https://www.imdb.com/title/tt0116629/?ref_=nv_sr_srsg_0",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Interstellar",
    "trailer": "https://www.youtube.com/watch?v=2LqzF5WauAw",
    "imdb": "https://www.imdb.com/title/tt0816692/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Kill Bill",
    "trailer": "https://www.youtube.com/watch?v=7kSuas6mRpk",
    "imdb": "https://www.imdb.com/title/tt0266697/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Little Miss Sunshine",
    "trailer": "https://www.youtube.com/watch?v=bQ7BZTMLImA",
    "imdb": "https://www.imdb.com/title/tt0449059/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Love Actually",
    "trailer": "https://www.youtube.com/watch?v=H9Z3_ifFheQ",
    "imdb": "https://www.imdb.com/title/tt0314331/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Made In America",
    "trailer": "https://www.youtube.com/watch?v=AEBIJRAkujM",
    "imdb": "https://www.imdb.com/title/tt3532216/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Maid In Manhattan",
    "trailer": "https://www.youtube.com/watch?v=v1dv-skGIYY",
    "imdb": "https://www.imdb.com/title/tt0252076/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Mailbu's Most Wanted",
    "trailer": "https://www.youtube.com/watch?v=clD_HL17t94",
    "imdb": "https://www.imdb.com/title/tt0328099/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Matilda",
    "trailer": "https://www.youtube.com/watch?v=mPvuVAUEETg",
    "imdb": "https://www.imdb.com/title/tt0117008/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Matrix",
    "trailer": "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    "imdb": "https://www.imdb.com/title/tt0133093/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Mean Girls",
    "trailer": "https://www.youtube.com/watch?v=KAOmTMCtGkI",
    "imdb": "https://www.imdb.com/title/tt0377092/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Moana",
    "trailer": "https://www.youtube.com/watch?v=yfCOEGyHMwc",
    "imdb": "https://www.imdb.com/title/tt3521164/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Moonrise Kingdom",
    "trailer": "https://www.youtube.com/watch?v=7N8wkVA4_8s",
    "imdb": "https://www.imdb.com/title/tt1748122/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Moonstruck",
    "trailer": "https://www.youtube.com/watch?v=M01_2CKL6PU",
    "imdb": "https://www.imdb.com/title/tt0093565/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Mrs. Doubtfire",
    "trailer": "https://www.youtube.com/watch?v=eJCPPcCOCPo",
    "imdb": "https://www.imdb.com/title/tt0107614/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Mulan",
    "trailer": "https://www.youtube.com/watch?v=MsAniqGowKE",
    "imdb": "https://www.imdb.com/title/tt0120762/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Nobody Knows",
    "trailer": "https://www.youtube.com/watch?v=mMP0KDKLwxw",
    "imdb": "https://www.imdb.com/title/tt0408664/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Nocturnal Animals",
    "trailer": "https://www.youtube.com/watch?v=-H1Ii1LjyFU",
    "imdb": "https://www.imdb.com/title/tt4550098/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Ocean's 8",
    "trailer": "https://www.youtube.com/watch?v=MFWF9dU5Zc0",
    "imdb": "https://www.imdb.com/title/tt5164214/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Ocean's Twelve",
    "trailer": "https://www.youtube.com/watch?v=k9uhRSLMORw",
    "imdb": "https://www.imdb.com/title/tt0349903/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Parasite",
    "trailer": "https://www.youtube.com/watch?v=SWSDQfJQhUg",
    "imdb": "https://www.imdb.com/title/tt6751668/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Pineapple Express",
    "trailer": "https://www.youtube.com/watch?v=nPlnjlhd-ME",
    "imdb": "https://www.imdb.com/title/tt0910936/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Pink Panther",
    "trailer": "https://www.youtube.com/watch?v=nrVcibhWMJI",
    "imdb": "https://www.imdb.com/title/tt0383216/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Pretty In Pink",
    "trailer": "https://www.youtube.com/watch?v=S-rAFVlr65k",
    "imdb": "https://www.imdb.com/title/tt0091790/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Pretty Woman",
    "trailer": "https://www.youtube.com/watch?v=2EBAVoN8L_U",
    "imdb": "https://www.imdb.com/title/tt0100405/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Purple Rain",
    "trailer": "https://www.youtube.com/watch?v=AuXK8ZbTmLk",
    "imdb": "https://www.imdb.com/title/tt0087957/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Romeo and Juliet",
    "trailer": "https://www.youtube.com/watch?v=8VOAxzgq42A",
    "imdb": "https://www.imdb.com/title/tt0117509/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Rosemary's Baby",
    "trailer": "https://www.youtube.com/watch?v=D0mcbEAP_yA",
    "imdb": "https://www.imdb.com/title/tt0063522/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Shaft",
    "trailer": "https://www.youtube.com/watch?v=T1ga1FgU10E",
    "imdb": "https://www.imdb.com/title/tt0067741/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Shakedown",
    "trailer": "https://www.youtube.com/watch?v=HAi3ngyfbFA",
    "imdb": "https://www.imdb.com/title/tt0096087/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "shakedown",
    "trailer": "https://www.pornhub.com/shakedown",
    "imdb": "https://www.pornhub.com/shakedown",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Shottas",
    "trailer": "https://www.youtube.com/watch?v=fvpaCJAMs2c",
    "imdb": "https://www.imdb.com/title/tt0281190/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Sister Act",
    "trailer": "https://www.youtube.com/watch?v=Q7j2aEJxxDY",
    "imdb": "https://www.imdb.com/title/tt0105417/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Sleepless in Seattle",
    "trailer": "https://www.youtube.com/watch?v=ahI9LaOGYcE",
    "imdb": "https://www.imdb.com/title/tt0108160/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Steel Magnolias",
    "trailer": "https://www.youtube.com/watch?v=XE6YsGadg7U",
    "imdb": "https://www.imdb.com/title/tt0098384/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Stepmom",
    "trailer": "https://www.youtube.com/watch?v=T8sAXDUFSCs",
    "imdb": "https://www.imdb.com/title/tt0120686/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Big Sick",
    "trailer": "https://www.youtube.com/watch?v=ilCT7moz_8I",
    "imdb": "https://www.imdb.com/title/tt5462602/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The blind Side",
    "trailer": "https://www.youtube.com/watch?v=gvqj_Tk_kuM",
    "imdb": "https://www.imdb.com/title/tt0878804/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Bodyguard",
    "trailer": "https://www.youtube.com/watch?v=zB8MckMxlJo",
    "imdb": "https://www.imdb.com/title/tt0103855/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Bourne Identity",
    "trailer": "https://www.youtube.com/watch?v=FpKaB5dvQ4g",
    "imdb": "https://www.imdb.com/title/tt0258463/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Bourne Supremacy",
    "trailer": "https://www.youtube.com/watch?v=Y-HqyyfBbSo",
    "imdb": "https://www.imdb.com/title/tt0372183/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Bourne Ultimatum",
    "trailer": "https://www.youtube.com/watch?v=wzXaC8w2bj8",
    "imdb": "https://www.imdb.com/title/tt0440963/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Breakfast club",
    "trailer": "https://www.youtube.com/watch?v=tDnWzxmZodM",
    "imdb": "https://www.imdb.com/title/tt0088847/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The conjuring",
    "trailer": "https://www.youtube.com/watch?v=ejMMn0t58Lc",
    "imdb": "https://www.imdb.com/title/tt1457767/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Holiday",
    "trailer": "https://www.youtube.com/watch?v=BDi5zH18vxU",
    "imdb": "https://www.imdb.com/title/tt0457939/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The House that Jack Built",
    "trailer": "https://www.youtube.com/watch?v=c6DuLPGZIoQ",
    "imdb": "https://www.imdb.com/title/tt4003440/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Interview",
    "trailer": "https://www.youtube.com/watch?v=Mj3uHftd5FQ",
    "imdb": "https://www.imdb.com/title/tt2788710/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Lorax",
    "trailer": "https://www.youtube.com/watch?v=1bHdzTUNw-4",
    "imdb": "https://www.imdb.com/title/tt1482459/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Nutty Professor",
    "trailer": "https://www.youtube.com/watch?v=FFVbS0qm0TI",
    "imdb": "https://www.imdb.com/title/tt0117218/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Outsiders",
    "trailer": "https://www.youtube.com/watch?v=Q0mBUs9Mcgg",
    "imdb": "https://www.imdb.com/title/tt0086066/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Parent Trap",
    "trailer": "https://www.youtube.com/watch?v=PMAhVpgzmRU",
    "imdb": "https://www.imdb.com/title/tt0120783/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Shining",
    "trailer": "https://www.youtube.com/watch?v=SqQl_vhEP4k",
    "imdb": "https://www.imdb.com/title/tt0081505/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "The Silence of the Lambs",
    "trailer": "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
    "imdb": "https://www.imdb.com/title/tt0102926/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Trois Couleurs",
    "trailer": "https://www.youtube.com/watch?v=Hxu6my_t4pM",
    "imdb": "https://www.imdb.com/title/tt0108394/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Troop Beverly Hills",
    "trailer": "https://www.youtube.com/watch?v=JwtyggDx-6E",
    "imdb": "https://www.imdb.com/title/tt0098519/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Uncut Gems",
    "trailer": "https://www.youtube.com/watch?v=sS6EE4D3tjQ",
    "imdb": "https://www.imdb.com/title/tt5727208/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Up!",
    "trailer": "https://www.youtube.com/watch?v=IBvk79DW-eg",
    "imdb": "https://www.imdb.com/title/tt1049413/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Waiting to Exhale",
    "trailer": "https://www.youtube.com/watch?v=j9xml1CxgXI",
    "imdb": "https://www.imdb.com/title/tt0114885/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Warriors",
    "trailer": "https://www.youtube.com/watch?v=4GxSwUcm_XE",
    "imdb": "https://www.imdb.com/title/tt0080120/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Waves",
    "trailer": "https://www.youtube.com/watch?v=T6zt39IADTY",
    "imdb": "https://www.imdb.com/title/tt8652728/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Weird Science",
    "trailer": "https://www.youtube.com/watch?v=MzkeqZdUEms",
    "imdb": "https://www.imdb.com/title/tt0090305/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  },
  {
    "title": "Woman On Top",
    "trailer": "https://www.youtube.com/watch?v=DzLKp0mR35Y",
    "imdb": "https://www.imdb.com/title/tt0206420/",
    "isAction": false,
    "isAnime": false,
    "isComedy": false,
    "isCrime": false,
    "isCult": false,
    "isForeign": false,
    "isRomance": false,
    "isFamily": false,
    "isDocumentary": false,
    "isDrama": false,
    "isHorror": false,
    "isSciFi": false
  }
]